### ISSUE TITLE
How to Uninstall This Plugin?

### ISSUE THREAD

**Issue by zalvis** [atikrahmanbd/redis-cpanel-plugin#1]
Hi,
I would like to know how to uninstall this plugin after installing it on cPanel/WHM server.

**Comment by windsofchange** [comment]
Why do you want to uninstall it, did you face any issues in getting it to work?

**Comment by zalvis** [comment]
No. But there should be an option to uninstall the plugin. As this is a third party plugin, so if the plugin goes dormant due to no further maintenance, then this could cause issues with cPanel. That's why uninstall option is mandatory one.

Although, I am hoping that, the developer will maintain the plugin for long run.
